const API_URL="";
const COMPETENCES=["Identitovigilance", "Hygiène", "Manutention et conduite du matériel", "Relation et communication avec le patient", "Compréhension des missions et utilisation du téléphone", "Repérage dans les bâtiments", "Communication avec les équipes", "Gestion des difficultés et imprévus", "Organisation et priorisation", "Autonomie globale"];
let agents=[];let currentAgent=null;
const $=s=>document.querySelector(s);
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function renderAgents(filter=""){const q=norm(filter);const list=agents.filter(a=>norm(`${a.nom}${a.prenom}${a.matricule||""}`).includes(q));$('#agent-count').textContent=list.length;$('#agent-list').innerHTML=list.length?list.map((a,i)=>`<button class="agent-card" data-index="${agents.indexOf(a)}"><div><strong>${escapeHtml(a.prenom)} ${escapeHtml(a.nom)}</strong><span>${escapeHtml(a.etape||'Dossier créé')}${a.matricule?' · Matricule '+escapeHtml(a.matricule):''}</span></div><span>›</span></button>`).join(''):`<div class="empty-state"><h3>Aucun agent enregistré</h3><p>Créez le premier dossier avec le bouton « Nouvel agent ».</p></div>`;document.querySelectorAll('.agent-card').forEach(b=>b.onclick=()=>openAgent(Number(b.dataset.index)))}
function renderCompetences(a){$('#competence-grid').innerHTML=COMPETENCES.map((c,i)=>`<label>${escapeHtml(c)}<select data-competence="${i}"><option>Non observé</option><option>Découvert</option><option>Réalisé avec accompagnement</option><option>Réalisé avec une aide ponctuelle</option><option>Autonome</option><option>À revoir prioritairement</option></select></label>`).join('');document.querySelectorAll('[data-competence]').forEach(s=>s.value=(a.evaluations||{})[COMPETENCES[Number(s.dataset.competence)]]||'Non observé')}
function renderAnswers(a){const data=a.agentAnswers||{};const entries=Object.entries(data);$('#agent-answers').innerHTML=entries.length?entries.map(([k,v])=>`<article class="answer-card"><strong>${escapeHtml(k)}</strong><p>${escapeHtml(v||'Non renseigné')}</p></article>`).join(''):'<div class="empty-state"><h3>Aucune réponse reçue</h3><p>Les formulaires transmis par l’agent apparaîtront ici.</p></div>'}
function openAgent(i){currentAgent=agents[i];$('#agent-name').textContent=`${currentAgent.prenom} ${currentAgent.nom}`;$('#agent-meta').textContent=currentAgent.matricule?`Matricule : ${currentAgent.matricule}`:'';document.querySelectorAll('[data-field]').forEach(el=>el.value=currentAgent[el.dataset.field]||'');renderCompetences(currentAgent);renderAnswers(currentAgent);$('#agent-file').hidden=false;$('#agent-file').scrollIntoView({behavior:'smooth'})}
function collectCurrent(){document.querySelectorAll('[data-field]').forEach(el=>currentAgent[el.dataset.field]=el.value);currentAgent.evaluations={};document.querySelectorAll('[data-competence]').forEach(el=>currentAgent.evaluations[COMPETENCES[Number(el.dataset.competence)]]=el.value)}
function similarAgents(nom,prenom){const n=norm(nom),p=norm(prenom);return agents.filter(a=>norm(a.nom)===n&&norm(a.prenom)===p)}
$('#new-agent').onclick=()=>{$('#new-agent-form').reset();$('#duplicate-warning').hidden=true;$('#new-agent-dialog').showModal()};
$('#create-agent').onclick=e=>{e.preventDefault();const f=new FormData($('#new-agent-form'));const a=Object.fromEntries(f.entries());if(!a.nom.trim()||!a.prenom.trim()||!a.dateArrivee){alert('Nom, prénom et date d’arrivée sont obligatoires.');return}const dup=similarAgents(a.nom,a.prenom);if(dup.length&&!confirm(`Un dossier existe déjà pour ${a.prenom} ${a.nom}. Voulez-vous créer quand même une nouvelle ligne ?`))return;agents.push({...a,etape:'Premier jour',agentAnswers:{},evaluations:{}});localStorage.setItem('ghe_chef_agents_demo',JSON.stringify(agents));$('#new-agent-dialog').close();renderAgents();openAgent(agents.length-1)};
$('#agent-search').oninput=e=>renderAgents(e.target.value);$('#close-file').onclick=()=>$('#agent-file').hidden=true;
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelector(`[data-panel="${t.dataset.tab}"]`).classList.add('active')});
$('#save-file').onclick=async()=>{collectCurrent();localStorage.setItem('ghe_chef_agents_demo',JSON.stringify(agents));$('#save-status').textContent=API_URL?'Enregistrement…':'Enregistré localement. Le script Google sera branché ensuite.';setTimeout(()=>$('#save-status').textContent='',3000)};
try{agents=JSON.parse(localStorage.getItem('ghe_chef_agents_demo')||'[]')}catch{agents=[]}renderAgents();
