const TEAM_API="https://script.google.com/macros/s/AKfycbzmelNrBU583V3CvOlle3cafAKEAZQ8NAX-peSN6D-yxFO3gX26SnVNUVd5xbwV3CUISg/exec";
const PLAN_API="https://script.google.com/macros/s/AKfycbwrhifE-4wl-YvKOjJI8HZ_g_ota7tajTKLY3jvLKEF9AvSPjIbVpqcSkSRcl5OdWV9/exec";
const TEAM_CACHE_PREFIX="ghe:team:v2:";
const TEAM_CACHE_FRESH_MS=60*1000;
const TEAM_CACHE_STALE_MS=10*60*1000;
const TEAM_ICS_CACHE_KEY="ghe:team:ics:v2";
const TEAM_ICS_CACHE_MS=24*60*60*1000;
const $=id=>document.getElementById(id);let selected=new Date(),weekStart=startWeek(selected),requestId=0,teamIcs="";
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startWeek(d){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(12,0,0,0);return x}
function arr(v){return Array.isArray(v)?v:[]}
function first(obj,keys,fallback=""){for(const k of keys)if(obj&&obj[k]!=null&&String(obj[k]).trim())return obj[k];return fallback}
function readTeamCache(dateIso){try{const raw=localStorage.getItem(TEAM_CACHE_PREFIX+dateIso);if(!raw)return null;const parsed=JSON.parse(raw);if(!parsed||typeof parsed.time!=="number"||!parsed.data)return null;return parsed}catch(_){return null}}
function writeTeamCache(dateIso,data){try{localStorage.setItem(TEAM_CACHE_PREFIX+dateIso,JSON.stringify({time:Date.now(),data}))}catch(_){}}
function renderWeek(){const end=add(weekStart,6);$("weekTitle").textContent=`${weekStart.toLocaleDateString("fr-FR",{day:"numeric",month:"long"})} — ${end.toLocaleDateString("fr-FR",{day:"numeric",month:"long"})}`;$("teamDays").innerHTML=Array.from({length:7},(_,i)=>{const d=add(weekStart,i),active=iso(d)===iso(selected);return `<button type="button" data-date="${iso(d)}" class="${active?'active':''}"><span>${d.toLocaleDateString("fr-FR",{weekday:"short"}).replace('.','')}</span><strong>${d.getDate()}</strong></button>`}).join("")}
function shiftEntries(jour){const candidates=[['M','Matin'],['J','Journée'],['J4','J4'],['S','Soir'],['N','Nuit']];const out=[];for(const [code,label] of candidates){const keys=[code,code.toLowerCase(),`shift${code}`,`shift_${code}`,`agents${code}`,`agents_${code}`];let list=[];for(const k of keys){if(Array.isArray(jour?.[k])){list=jour[k];break}}if(list.length)out.push({code,label,list})}if(!out.length){const shifts=jour?.shifts||jour?.planning||jour?.equipes;if(shifts&&typeof shifts==='object'&&!Array.isArray(shifts)){for(const [k,v] of Object.entries(shifts))if(Array.isArray(v)&&v.length)out.push({code:k.toUpperCase(),label:k,list:v})}}return out}
function personName(a){return first(a,['prenom','agent','nomPrenom','nom_complet','nom'],'Agent')}
function ghe(a){return first(a,['ghe','GHE','numero_ghe','numeroGhe'],'')}
function renderPeople(list){return arr(list).map(a=>`<div class="team-person"><div><strong>${esc(String(personName(a)).toUpperCase())}</strong>${ghe(a)?`<small>GHE ${esc(ghe(a))}</small>`:''}</div></div>`).join('')||'<div class="team-empty">Aucun agent détecté</div>'}
function renderAlerts(jour){const rows=[...arr(jour?.gheManquants),...arr(jour?.codesInconnus),...arr(jour?.alertesSource)];if(!rows.length)return'';return `<section class="team-section warning"><h2>À vérifier</h2>${rows.map(x=>`<div class="team-alert">${esc(typeof x==='string'?x:JSON.stringify(x))}</div>`).join('')}</section>`}
function renderImportant(title,items,kind){if(!items.length)return'';return `<section class="team-section ${kind}"><h2>${title}<span>${items.length}</span></h2>${items.map(item=>{const name=first(item,['titre','nom','formation','stagiaire','nomPrenom'],'Information');const time=first(item,['horaire','heure','creneau'],'');const agents=arr(item.agents||item.referents);return `<article class="team-important"><strong>${esc(name)}</strong>${time?`<small>${esc(time)}</small>`:''}${agents.length?`<div class="team-mini-list">${renderPeople(agents)}</div>`:''}</article>`}).join('')}</section>`}
function render(data){const jour=data?.jour||data||{};const shifts=shiftEntries(jour),formations=arr(jour.formations),stagiaires=arr(jour.stagiaires);let html=`<section class="team-summary"><div><strong>${shifts.reduce((n,s)=>n+s.list.length,0)}</strong><span>agents</span></div><div><strong>${formations.length}</strong><span>formations</span></div><div><strong>${stagiaires.length}</strong><span>stagiaires</span></div></section>`;html+=shifts.map(s=>`<section class="team-section"><h2><span class="shift-pill">${esc(s.code)}</span>${esc(s.label)}<span>${s.list.length}</span></h2>${renderPeople(s.list)}</section>`).join('');html+=renderImportant('Formations',formations,'formations');html+=renderImportant('Stagiaires / référents',stagiaires,'stagiaires');html+=renderAlerts(jour);$("teamContent").innerHTML=html;$("teamContent").hidden=false;$("teamStatus").hidden=true}
function loadDate(dateIso){const id=++requestId;const cached=readTeamCache(dateIso);const age=cached?Date.now()-cached.time:Infinity;if(cached&&age<TEAM_CACHE_STALE_MS)render(cached.data);else{$("teamStatus").hidden=false;$("teamStatus").textContent="Chargement de l’organisation du "+new Date(dateIso+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})+'…'}if(cached&&age<TEAM_CACHE_FRESH_MS)return;const cb='gheTeam_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');const clean=()=>{try{delete window[cb]}catch(_){ }script.remove()};window[cb]=data=>{if(id!==requestId){clean();return}try{if(!data||data.ok===false)throw new Error(data?.erreur||'Données collectives indisponibles');writeTeamCache(dateIso,data);render(data)}catch(e){if(!cached)$("teamStatus").textContent=e.message}clean()};script.onerror=()=>{if(id===requestId&&!cached)$("teamStatus").textContent="Impossible de charger l’organisation.";clean()};script.src=`${TEAM_API}?mode=jsonp&date=${encodeURIComponent(dateIso)}&callback=${encodeURIComponent(cb)}&t=${Date.now()}`;document.body.appendChild(script)}
function applyTeamIcs(url){teamIcs=url||"";if(teamIcs){$("teamSubscribeStatus").textContent="Calendrier collectif permanent détecté. Une fois abonné, les mises à jour sont récupérées par votre agenda.";$("teamSubscribeActions").hidden=false;$("teamApple").href=teamIcs.replace(/^https:\/\//i,'webcal://')}else{$("teamSubscribeStatus").textContent="La vue Esprit d’équipe fonctionne. Le flux d’abonnement collectif n’est pas exposé par les passerelles actuelles : je ne génère pas de faux lien."}}
async function detectTeamIcs(){try{const cached=JSON.parse(localStorage.getItem(TEAM_ICS_CACHE_KEY)||"null");if(cached&&cached.url&&Date.now()-Number(cached.time||0)<TEAM_ICS_CACHE_MS){applyTeamIcs(cached.url);return}}catch(_){}const candidates=[];for(const base of [TEAM_API,PLAN_API])for(const mode of ['collectif-ics','collectif_ics','ics_collectif','team_ics','esprit_ics']){const u=new URL(base);u.searchParams.set('mode',mode);candidates.push(u.toString())}for(const url of candidates){try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),3500);const r=await fetch(url,{cache:'no-store',signal:controller.signal});clearTimeout(timeout);const text=await r.text();if(r.ok&&text.includes('BEGIN:VCALENDAR')){teamIcs=url;try{localStorage.setItem(TEAM_ICS_CACHE_KEY,JSON.stringify({time:Date.now(),url}))}catch(_){}break}}catch(_){}}applyTeamIcs(teamIcs)}
$("teamDays").addEventListener('click',e=>{const b=e.target.closest('[data-date]');if(!b)return;selected=new Date(b.dataset.date+'T12:00:00');weekStart=startWeek(selected);renderWeek();loadDate(b.dataset.date)});$("prevWeek").addEventListener('click',()=>{weekStart=add(weekStart,-7);selected=new Date(weekStart);renderWeek();loadDate(iso(selected))});$("nextWeek").addEventListener('click',()=>{weekStart=add(weekStart,7);selected=new Date(weekStart);renderWeek();loadDate(iso(selected))});$("teamAndroid").addEventListener('click',async()=>{if(!teamIcs)return;try{await navigator.clipboard.writeText(teamIcs);$("teamSubscribeStatus").textContent="Lien permanent copié. Ajoutez-le à Google Agenda depuis « À partir de l’URL »."}catch(_){$("teamSubscribeStatus").textContent=teamIcs}});
GHEAuth.ready.then(()=>{selected=new Date();weekStart=startWeek(selected);renderWeek();loadDate(iso(selected));detectTeamIcs()});