/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 05953f1dde2f6158d5b713174203f2e7)
interface __BaseEnv_Env {
	DOCUMENTS: R2Bucket;
	DB: D1Database;
	LOGIN_IP_LIMITER: RateLimit;
	LOGIN_GLOBAL_LIMITER: RateLimit;
	SHARE_LINK_LIMITER: RateLimit;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}