const EVALUATION_SECTIONS = [
  {title:"I — Aptitude au service", observation:"observations_1", criteria:["Aptitude à travailler sans contrôle","Efficacité","Esprit pratique","Souci de perfectionnement"]},
  {title:"II — Exécution du travail", observation:"observations_2", criteria:["Rapidité d'exécution","Qualité du travail","Sens de l'organisation","Initiative"]},
  {title:"III — Travail en commun", observation:"observations_3", criteria:["Caractère","Relation avec le personnel infirmier","Contact avec les autres agents du service","Contact avec l’encadrement"]},
  {title:"IV — Comportement envers les malades", observation:"observations_4", criteria:["Disponibilité","Discrétion","Attitude envers les visiteurs"]},
  {title:"V — Tenue, ponctualité, assiduité", observation:"observations_5", criteria:["Utilisation du temps de travail","Attitude générale","Propreté dans la tenue","Régularité","Ponctualité / assiduité"]}
];
const LEVELS=["Insuffisant","Médiocre","Passable","Assez bien","Bien","Très bien","Exceptionnel"];
const slug=s=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"").toLowerCase();
const state={agent:null,evaluations:[],locked:false};
const el=id=>document.getElementById(id);

function renderCriteria(){
  el("criteria").innerHTML=EVALUATION_SECTIONS.map((section,si)=>`<fieldset class="evaluation-section"><legend>${esc(section.title)}</legend>${section.criteria.map(label=>{const name="critere_"+slug(label);return `<div class="criterion"><div class="criterion-label">${esc(label)} *</div><div class="level-options">${LEVELS.map((level,i)=>`<label><input type="radio" name="${name}" value="${esc(level)}" required><span>${i+1}<small>${esc(level)}</small></span></label>`).join("")}</div></div>`}).join("")}<label>Observations de la section<textarea name="${section.observation}"></textarea></label></fieldset>`).join("");
}
function today(){return new Date().toISOString().slice(0,10)}
function payload(){const data=Object.fromEntries(new FormData(el("evaluationForm")).entries());data.id_agent=AgentContext.id;data.criteres={};EVALUATION_SECTIONS.flatMap(s=>s.criteria).forEach(label=>{data.criteres[label]=data["critere_"+slug(label)]||"";delete data["critere_"+slug(label)];});return data}
function resetForm(){state.locked=false;el("evaluationForm").reset();el("evaluationForm").elements.date_evaluation.value=today();el("evaluationForm").elements.lyon_le.value=today();el("evaluationForm").elements.service.value="STIP";el("formKicker").textContent="Nouvelle évaluation";el("formTitle").textContent="Brouillon";el("pdfBtn").hidden=true;el("pdfBtn").removeAttribute("href");lockForm(false);el("confirmFinal").checked=false;el("finalizeBtn").disabled=true;el("formStatus").className="status"}
function lockForm(value){state.locked=value;el("evaluationForm").querySelectorAll("input,textarea,select").forEach(x=>{if(x.id!=="confirmFinal")x.disabled=value});el("saveBtn").hidden=value;el("finalizeBtn").hidden=value;el("confirmFinal").closest(".final-warning").hidden=value}
function fillForm(ev){resetForm();const f=el("evaluationForm").elements;["id_evaluation","grade","service","date_evaluation","evaluateur","lyon_le","garder_agent","observations_1","observations_2","observations_3","observations_4","observations_5","observations_generales"].forEach(k=>{if(f[k])f[k].value=ev[k]||""});Object.entries(ev.criteres||{}).forEach(([label,value])=>{const radio=document.querySelector(`[name="critere_${slug(label)}"][value="${CSS.escape(value)}"]`);if(radio)radio.checked=true});el("formKicker").textContent=ev.statut==="VALIDE"?"Version officielle":"Brouillon";el("formTitle").textContent=`${ev.id_evaluation} · version ${ev.version}`;if(ev.url_document){el("pdfBtn").href=ev.url_document;el("pdfBtn").hidden=false}lockForm(ev.statut==="VALIDE")}
function renderList(){const box=el("evaluationList");if(!state.evaluations.length){box.innerHTML='<div class="empty">Aucune évaluation. Créez le premier brouillon.</div>';return}box.innerHTML=state.evaluations.map(ev=>`<button class="evaluation-row" data-id="${esc(ev.id_evaluation)}" type="button"><span><strong>${esc(displayDate(ev.date_evaluation))}</strong><small>${esc(ev.evaluateur||"Évaluateur non renseigné")}</small></span><span class="badge ${ev.statut==="VALIDE"?"verifie":"provisoire"}">${esc(ev.statut)} · v${esc(ev.version)}</span></button>`).join("");box.querySelectorAll("button").forEach(b=>b.onclick=()=>openEvaluation(b.dataset.id))}
async function loadList(){setStatus(el("listStatus"),"warn","Chargement des évaluations…");try{const d=await apiGet("listEvaluations",{id:AgentContext.id});state.evaluations=d.evaluations||[];renderList();el("listStatus").className="status"}catch(e){setStatus(el("listStatus"),"err",esc(e.message))}}
async function openEvaluation(id){setStatus(el("formStatus"),"warn","Chargement…");el("formPanel").hidden=false;try{const d=await apiGet("getEvaluation",{id});fillForm(d.evaluation);el("formPanel").scrollIntoView({behavior:"smooth"})}catch(e){setStatus(el("formStatus"),"err",esc(e.message))}}
async function submit(finalize){const form=el("evaluationForm");if(!form.reportValidity())return;if(finalize&&!el("confirmFinal").checked)return;setStatus(el("formStatus"),"warn",finalize?"Validation et génération du PDF…":"Enregistrement et vérification…");el("saveBtn").disabled=true;el("finalizeBtn").disabled=true;try{const action=finalize?"finalizeEvaluation":"saveEvaluationDraft";const d=await apiPost(action,payload());fillForm(d.evaluation);setStatus(el("formStatus"),"ok",finalize?"✓ Version validée. Le PDF officiel est disponible.":"✓ Brouillon enregistré et relu.");await loadList()}catch(e){setStatus(el("formStatus"),"err","Échec : "+esc(e.message))}finally{el("saveBtn").disabled=false;el("finalizeBtn").disabled=!el("confirmFinal").checked}}

document.addEventListener("DOMContentLoaded",async()=>{renderCriteria();try{state.agent=await AgentContext.load();await loadList()}catch(_){}el("newBtn").onclick=()=>{resetForm();el("formPanel").hidden=false;el("formPanel").scrollIntoView({behavior:"smooth"})};el("closeBtn").onclick=()=>{el("formPanel").hidden=true};el("saveBtn").onclick=()=>submit(false);el("finalizeBtn").onclick=()=>submit(true);el("confirmFinal").onchange=e=>{el("finalizeBtn").disabled=!e.target.checked}});
